aichat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('board/', include('apps.board.urls')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('bot/', include('apps.bot.urls')),
    path('chat/', include('apps.chat.urls')),
    path('summernote/', include('django_summernote.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views

from apps.users import views 

app_name = 'users'

urlpatterns = [
    path('join/', views.join),
    path('login/', auth_views.LoginView.as_view(
        template_name='users/login.html',
        redirect_authenticated_user=True
        ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

apps/users/models.py
from django.db import models

# # Create your models here.
# class users(models.Model):
#     username = models.CharField(max_length=50)
#     password = models.CharField(max_length=50)

#     userimg = models.ImageField(null=True)

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# class joinForm(forms.ModelForm):
#     class Meta:
#         model = users
#         fields = ['username', 'password']

class joinForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import joinForm

# from .models import users

# Create your views here.
def join(request):
    if request.method == 'GET':
        form = joinForm()
        return render(request, 'users/join.html', {'form':form})
    elif request.method == 'POST':
        form = joinForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')
        else:
            return render(request, 'users/join.html', {'form':form})

templates/users/join.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>회원가입</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'users/join_style.css' %}"/>
    </head>
    
    <body>
        <div class="container">
            <h>AI chat 회원가입</h>
            {{ form.errors }}
            <form class="forms" action="" method="post">
                {% csrf_token %}
                <p>아이디</p>
                <div class="form">{{ form.username }}</div>
                <p>비밀번호</p>
                <div class="form">{{ form.password1 }}</div>
                <p>비밀번호 확인</p>
                <div class="form">{{ form.password2 }}</div>
                <p><input class="submit" id="forms" type="submit" value="가입"></p>
            </form>
        </div>
    </body>
</html>

templates/users/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>로그인</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'users/login_style.css' %}"/>
    </head>

    <body>
        <div class="container">
            <h>AI chat 로그인</h>
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                {% endif %}
            <form class="forms" method="post" action="{% url 'users:login' %}">
                {% csrf_token %}
                <p>아이디</p>
                <div class="form">{{ form.username }}</div>
                <p>비밀번호</p>
                <div class="form">{{ form.password }}</div>
                <button class="submit" type="submit">로그인</button>
            </form>
        </div>
    </body>
</html>